# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jit-app" do
  version "0.3.0"
  sha256 "fb6566e7757cf2daa03a28022442d41737e0a71741612cf54578275883983cb5"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version}/JitPass-#{version}-arm64.zip"
  name "JitPass"
  desc "Menu bar app for jit, the just-in-time secrets tool"
  homepage "https://github.com/jitpass/jit-app"

  depends_on cask: "jitpass/tap/jitpass"
  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "JitPass.app"

  zap trash: "~/Library/Preferences/com.jitpass.app.plist"
end
