# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jit-app" do
  version "0.5.0"
  sha256 "39198c4b18e56230b9d267b4ad0a97ab72be4d7a7992986fc2e1d4a7374bce0d"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version}/JitPass-#{version}-arm64.zip"
  name "JitPass"
  desc "Menu bar app for jit, the just-in-time secrets tool"
  homepage "https://github.com/jitpass/jit-app"

  depends_on cask: "jitpass/tap/jitpass"
  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "JitPass.app"

  zap trash: "~/Library/Preferences/com.jitpass.app.plist"
end
