# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jit-app" do
  version "0.8.1"
  sha256 "29510d1dd6f3ef62645e67f1ef5cf4a4b9a6288528cf74a629cdf0364165964a"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version}/JitPass-#{version}-arm64.zip"
  name "JitPass"
  desc "Menu bar app for jit, the just-in-time secrets tool"
  homepage "https://github.com/jitpass/jit-app"

  depends_on cask: "jitpass/tap/jitpass"
  depends_on macos: :sonoma
  depends_on arch: :arm64

  app "JitPass.app"

  zap trash: "~/Library/Preferences/com.jitpass.app.plist"
end
