# This file was generated by GoReleaser. DO NOT EDIT.
cask "jitpass" do
  version "0.92.2"

  on_macos do
    on_arm do
      sha256 "dc2dc28525acd8cdb9e273e86e5ad324158c2512bc43d1f799c818c921a40d44"
      url "https://dl.jitpass.com/jitpass/jit/releases/download/v#{version}/jitpass_darwin_arm64.tar.gz",
        verified: "dl.jitpass.com/"
    end
  end

  name "jitpass"
  desc "Local-first developer secret runtime"
  homepage "https://github.com/jitpass/jit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jit"
  bash_completion "completions/jit.bash"
  fish_completion "completions/jit.fish"
  zsh_completion "completions/_jit"

  # No zap stanza required

end
