# This file was generated by GoReleaser. DO NOT EDIT.
cask "jitpass" do
  version "0.80.1"

  on_macos do
    on_arm do
      sha256 "d385223fcd67d98a8bf88099faf9740a5d2e2eca12240e2132c8871594a30bc3"
      url "https://github.com/jitpass/jit/releases/download/v#{version}/jitpass_darwin_arm64.tar.gz"
    end
  end

  name "jitpass"
  desc "Local-first developer secret runtime"
  homepage "https://github.com/jitpass/jit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jit"

  # No zap stanza required

end
