# This file was generated by GoReleaser. DO NOT EDIT.
cask "jitpass" do
  version "1.5.5"

  on_macos do
    on_arm do
      sha256 "a3efbf69534adea468c9bc85d3e0d24e184e48fa70d1c3a95f8890e76316f4a5"
      url "https://dl.jitpass.com/jitpass/jit/releases/download/v#{version}/jitpass_darwin_arm64.tar.gz"
    end
  end

  name "jitpass"
  desc "Local-first developer secret runtime"
  homepage "https://github.com/jitpass/jit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jit"
  bash_completion "completions/jit.bash"
  fish_completion "completions/jit.fish"
  zsh_completion "completions/_jit"

  # No zap stanza required

end
